[build]
  publish="./build"
  base = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer"
    X-Frame-Options = "SAMEORIGIN"
    Access-Control-Allow-Origin = "*"
    X-Content-Type-Options = "nosniff"